<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNkxMak5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNkxMak5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNkxMak5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNkxMak5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNkxMak5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NkxMak5',
    'container.build_id' => 'e978abf0',
    'container.build_time' => 1565280271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNkxMak5');
